import type { Vehicle } from "../types";
import { getSupabaseClient } from "../services/supabase";
import { DataError, toDataError, toNumber, toText } from "./dataError";
import { getAuthenticatedUserId } from "./session";

/**
 * Supabase-backed vehicle data. Supabase is the source of truth; the owner is
 * always the authenticated Supabase user id, never a value from the UI.
 */

const VEHICLE_TABLE = "vehicles";
const VEHICLE_COLUMNS = "id, owner_id, name, make, model, color, plate, seats, is_default, created_at, updated_at";

export interface VehicleRow {
  id: string;
  owner_id: string;
  name: string;
  make: string;
  model: string;
  color: string | null;
  plate: string;
  seats: number;
  is_default: boolean;
  created_at: string;
  updated_at: string;
}

/**
 * What the UI may set. `id`, `userId` and `isDefault` are intentionally
 * absent: the owner always comes from the Supabase session, and the default
 * flag is only ever changed through `setDefaultVehicle` so the
 * `vehicles_one_default_per_owner` partial unique index can never be violated.
 */
export interface VehicleDraft {
  name: string;
  make: string;
  model: string;
  color: string;
  plate: string;
  seats: number;
}

const rowToVehicle = (row: VehicleRow): Vehicle => ({
  id: row.id,
  userId: row.owner_id,
  name: toText(row.name),
  make: toText(row.make),
  model: toText(row.model),
  color: toText(row.color),
  plate: toText(row.plate),
  seats: toNumber(row.seats, 1),
  isDefault: Boolean(row.is_default),
});

const toPatch = (draft: VehicleDraft): Record<string, unknown> => ({
  name: draft.name.trim(),
  make: draft.make.trim(),
  model: draft.model.trim(),
  color: draft.color.trim(),
  plate: draft.plate.trim().toUpperCase(),
  seats: draft.seats,
});

const validateDraft = (draft: VehicleDraft): void => {
  if (!draft.name.trim()) throw new DataError("Give the vehicle a name.", "invalid");
  if (!draft.make.trim()) throw new DataError("Enter the vehicle make.", "invalid");
  if (!draft.model.trim()) throw new DataError("Enter the vehicle model.", "invalid");
  if (!draft.plate.trim()) throw new DataError("Enter the registration plate.", "invalid");
  if (!Number.isInteger(draft.seats) || draft.seats < 1 || draft.seats > 12) {
    throw new DataError("Vehicle seats must be between 1 and 12.", "invalid");
  }
};

/** Vehicles owned by the authenticated user. */
export const listVehicles = async (): Promise<Vehicle[]> => {
  const ownerId = await getAuthenticatedUserId();
  const client = getSupabaseClient();

  const { data, error } = await client
    .from(VEHICLE_TABLE)
    .select(VEHICLE_COLUMNS)
    .eq("owner_id", ownerId)
    .order("is_default", { ascending: false })
    .order("created_at", { ascending: true });

  if (error) throw toDataError(error, "load");
  return ((data ?? []) as VehicleRow[]).map(rowToVehicle);
};

export const getVehicleById = async (vehicleId: string): Promise<Vehicle | null> => {
  if (!vehicleId) return null;
  const client = getSupabaseClient();

  const { data, error } = await client
    .from(VEHICLE_TABLE)
    .select(VEHICLE_COLUMNS)
    .eq("id", vehicleId)
    .maybeSingle();

  if (error) throw toDataError(error, "load");
  return data ? rowToVehicle(data as VehicleRow) : null;
};

/**
 * Inserts a new vehicle for the authenticated user.
 *
 * The id is generated by Postgres (`gen_random_uuid()`); the client never
 * supplies one. `is_default` is always false on insert and is only promoted
 * afterwards through `setDefaultVehicle`, because the partial unique index
 * allows just one default per owner and promoting during the insert would
 * collide with an existing default.
 */
export const createVehicle = async (draft: VehicleDraft): Promise<Vehicle> => {
  validateDraft(draft);
  const ownerId = await getAuthenticatedUserId();
  const client = getSupabaseClient();

  const { data, error } = await client
    .from(VEHICLE_TABLE)
    .insert({ ...toPatch(draft), owner_id: ownerId })
    .select(VEHICLE_COLUMNS)
    .single();

  if (error) {
    if (import.meta.env.DEV) {
      console.error("[vehicles] insert rejected", {
        code: error.code,
        message: error.message,
        details: error.details,
        hint: error.hint,
      });
    }
    if (error.code === "23505") {
      throw new DataError("You already have a vehicle with this registration plate.", "duplicate", error);
    }
    if (error.code === "42501") {
      throw new DataError("You do not have permission to add a vehicle.", "forbidden", error);
    }
    if (error.code === "23503") {
      throw new DataError(
        "Your profile is still being set up. Try again in a moment.",
        "invalid",
        error,
      );
    }
    throw toDataError(error, "create");
  }

  if (import.meta.env.DEV) {
    console.info("[vehicles] created", { id: data?.id, ownerId });
  }

  const created = rowToVehicle(data as VehicleRow);
  // A member with no default yet gets one automatically, so Offer Ride always
  // has a vehicle preselected. This is a convenience, not a rule the UI depends
  // on: if the promotion fails the vehicle still exists and is usable.
  if (!created.isDefault) {
    const { data: existingDefault } = await client
      .from(VEHICLE_TABLE)
      .select("id")
      .eq("owner_id", ownerId)
      .eq("is_default", true)
      .limit(1);

    if (!existingDefault || existingDefault.length === 0) {
      try {
        await setDefaultVehicle(created.id);
        return { ...created, isDefault: true };
      } catch (error) {
        if (import.meta.env.DEV) console.warn("[vehicles] auto-default skipped", error);
        // Return the row as the database actually holds it. Claiming
        // `isDefault: true` after a failed promotion would hand the caller a
        // vehicle that is not the default, and the first reader to trust it
        // would preselect the wrong car when offering a ride.
        return created;
      }
    }
  }
  return created;
};

export const updateVehicle = async (vehicleId: string, draft: VehicleDraft): Promise<Vehicle> => {
  validateDraft(draft);
  await getAuthenticatedUserId();
  const client = getSupabaseClient();

  const { data, error } = await client
    .from(VEHICLE_TABLE)
    .update(toPatch(draft))
    .eq("id", vehicleId)
    .select(VEHICLE_COLUMNS)
    .maybeSingle();

  if (error) {
    if (error.code === "23505") {
      throw new DataError("You already have a vehicle with this registration plate.", "duplicate", error);
    }
    throw toDataError(error, "update");
  }
  if (!data) {
    throw new DataError("We could not find that vehicle. It may have been removed.", "not-found");
  }
  return rowToVehicle(data as VehicleRow);
};

export const deleteVehicle = async (vehicleId: string): Promise<void> => {
  await getAuthenticatedUserId();
  const client = getSupabaseClient();

  const { error } = await client.from(VEHICLE_TABLE).delete().eq("id", vehicleId);
  if (error) throw toDataError(error, "delete");
};

/**
 * Promotes one of the caller's vehicles to be their default.
 *
 * Demoting the previous default and promoting the new one happens inside a
 * single `set_default_vehicle` database function. Doing it from React in two
 * statements is not merely slower: `vehicles_one_default_per_owner` is a
 * partial unique index on `(owner_id) where is_default`, so the promote would
 * be rejected with a 23505 while the old default was still flagged.
 */
export const setDefaultVehicle = async (vehicleId: string): Promise<void> => {
  await getAuthenticatedUserId();
  const client = getSupabaseClient();

  const { error } = await client.rpc("set_default_vehicle", {
    target_vehicle_id: vehicleId,
  });

  if (error) {
    if (/your own vehicle/i.test(error.message ?? "")) {
      throw new DataError("You can only set one of your own vehicles as the default.", "forbidden", error);
    }
    throw toDataError(error, "update");
  }
};

export const listVehiclesByIds = async (vehicleIds: string[]): Promise<Vehicle[]> => {
  const unique = [...new Set(vehicleIds.filter(Boolean))];
  if (unique.length === 0) return [];
  const client = getSupabaseClient();

  const { data, error } = await client
    .from(VEHICLE_TABLE)
    .select(VEHICLE_COLUMNS)
    .in("id", unique);

  if (error) throw toDataError(error, "load");
  return ((data ?? []) as VehicleRow[]).map(rowToVehicle);
};

export { rowToVehicle, VEHICLE_COLUMNS, VEHICLE_TABLE };
